FROM python:3.10

WORKDIR /app

# Install domain-specific packages
COPY docker_dependencies.txt /app/
RUN pip install --no-cache-dir -r docker_dependencies.txt

# Do not set an ENTRYPOINT so the container can run arbitrary commands

